### ISSUE TITLE
Can the sheet parameter be optional?

### ISSUE THREAD

**Issue by kjprice** [joyrexus/parse-xl#1]
Currently, you have to know beforehand what sheet you want. Would it be possible to optionally pass the `sheet` parameter, and if it does not exist, then just return the entire workbook? I am looking at version 0.0.6.

**Comment by joyrexus** [comment]
I don't have a particular need for that, but I'd except a pull request that adds a `data()` or `workbook()` function to the `Parser` prototype that just returns the [full dataset/workbook](https://github.com/joyrexus/parse-xl/blob/master/index.js#L11).
